name: Host Windows CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read


jobs:
  host_windows_latest:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9.x'
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: ccache gcc
    - run: pip install meson ninja
    - run: meson setup build -Dwith_tests=enabled
      env:
        CC: ccache gcc
    - run: meson test -C build -v
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: Windows_Meson_Testlog
        path: build/meson-logs/testlog.txt

  host_windows_2019:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.9.x'
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: ccache gcc
    - run: pip install meson ninja
    - run: meson setup build -Dwith_tests=enabled
      env:
        CC: ccache gcc
    - run: meson test -C build -v
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: Windows_2019_Meson_Testlog
        path: build/meson-logs/testlog.txt

  host_windows_2022:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.9.x'
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: ccache gcc
    - run: pip install meson ninja
    - run: meson setup build -Dwith_tests=enabled
      env:
        CC: ccache gcc
    - run: meson test -C build -v
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: Windows_2022_Meson_Testlog
        path: build/meson-logs/testlog.txt
